#!/bin/bash
#Set job requirements
#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=trainModel
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=00:02:01
#SBATCH --output=slurm_output_%A.out 
#SBATCH --mail-type=BEGIN,END
#SBATCH --mail-user=i.a.j.van.miert@student.vu.nl

model purge 
module load 2022
module load Anaconda3/2022.05

#Your job starts in the directory where you call sbatch
cd $HOME/pifpaf/test
#Activate your environment
source activate pifpaf

python process_folders_testset.py --input_folder /home/ivanmiert/pifpaf/test/event_folder --output_folder /scratch-shared/ivanmiert/testset/pifpaf4

